////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /plugins/projects/
:language: en_US
:page-alternativeEditUrl: https://github.com/apache/incubator-hop/edit/master/plugins/misc/projects/src/main/doc/projects.adoc
:openvar: ${
:closevar: }
= Projects & Environments

This document explains the basic structure and working of the 'projects' plugin

== Architecture

We want to make it easy for a developer to use one or more projects alongside each other.
A project is the collection of all the files you need in your data orchestration solution. This typically includes metadata, pipelines, workflows, reference files, documentation and so on.  To match standard development best practices you would check all these files into a version control system like git.

What are typically not included in this set of files are the variable values that you want to make the project run correctly in a certain environment.  For example on a development laptop you might want to set a variable DB_HOSTNAME to localhost and on a production server this value might point to the production database server.
Because of this you can define (Project Lifecycle) Environments in Hop which wrap around a project by name and include one or more configuration files.  You want these configuration files to be stored outside of the project folder and perhaps into a separate version control repository.

== Projects

The 2 main things that define a project are its name and its home folder.
Projects and environments as such are defined in the central Hop configuration file hop-config.json.
By default this file lives in the config/ folder of your Hop client distribution.  You can change that folder by setting the HOP_CONFIG_FOLDER environment variable on your system.

In ```hop-config.json``` you'll find a ```"projectsConfig"``` section. By default it contains the following:

[source,json]
----
{
  "projectsConfig" : {
    "enabled" : true,
    "projectMandatory" : true,
    "environmentMandatory" : false,
    "defaultProject" : "default",
    "defaultEnvironment" : null,
    "standardParentProject" : "default",
    "standardProjectsFolder" : null,
    "projectConfigurations" : [ {
      "projectName" : "default",
      "projectHome" : "config/projects/default",
      "configFilename" : "project-config.json"
    }, {
      "projectName" : "samples",
      "projectHome" : "config/projects/samples",
      "configFilename" : "project-config.json"
    } ],
    "lifecycleEnvironments" : [ ],
    "projectLifecycles" : [ ]
  }
}
----

As you can see the standard Hop client distribution defines 2 projects: default and samples.

Every project has extra metadata and settings stored in a project configuration file called ```project-config.json```.  For the samples project this would be ```config/projects/samples/project-config.json```.
Let's take a look at it:

[source,json]
----
{
  "metadataBaseFolder" : "${PROJECT_HOME}/metadata",
  "unitTestsBasePath" : "${PROJECT_HOME}",
  "dataSetsCsvFolder" : "${PROJECT_HOME}/datasets",
  "enforcingExecutionInHome" : true,
  "parentProjectName" : "default",
  "config" : {
    "variables" : [ ]
  }
}
----

=== Variables

You can define variables on a project level as well.  This makes it handy to reference things like input and output folders which are not sensitive to being checked into version control.

=== Parent projects

As you can see from the project configuration file, a project can have a parent from which it will inherit all the metadata objects as well as all the variables that are defined in it.

=== Configuration using Hop GUI

The main toolbar in the Hop GUI offers buttons to add, edit and delete a project.

=== Configuration on the command line

The ```hop-conf``` script offers many options to edit everything projects related.
Please note that these commands never change the content of a project itself.  They only change the way it is configured on your system.

==== Creating a project

[source,bash]
----
$ sh hop-conf.sh --project-create --project hop2 --project-home /home/user/projects/hop2 --project-parent default
Creating project 'hop2'
Project 'hop2' was created for home folder : /home/user/projects/hop2
Configuration file for project 'hop2' was saved to : /home/user/projects/hop2/project-config.json
----

==== Modifying a project

This command adds a variable to the project configuration:

[source,bash]
----
$ sh hop-conf.sh --project-modify --project hop2 --project-variables INPUT_FOLDER=input/
Project configuration for 'hop2' was modified in <path-to-hop>/config/hop-config.json
Project settings for 'hop2' were modified in file /home/user/projects/hop2/project-config.json
----

If we look at the project-config.json file we'll see that the variable/value pair was added:
[source,json]
----
{
  "config" : {
    "variables" : [ {
      "name" : "INPUT_FOLDER",
      "value" : "input/"
    } ]
  }
}
----

===== Deleting a project

The following deletes a project from the Hop configuration file:

[source,bash]
----
$ sh hop-conf.sh -pd -p hop2
Project 'hop2 was removed from the configuration
----

== Environments

Environment is short for Project Lifecycle Environment.  It describes the phase of a project in its lifecycle moving from Development to Test to Acceptance to Production.  It can also describe a project in a continuous integration environment and so on.  As such the following attributes define an environment:

* Its name
* The name of the project
* The phase
* The configuration files you want to use to define the environment specific variables

=== Configuration using Hop GUI

The main toolbar in the Hop GUI offers buttons to add, edit and delete an environment.
Please note that you can add non-existing configuration files in the environment dialog.  When editing the Hop GUI will ask you if you want to create the file.

