[[Projects]]
= Project concepts

_**WORK IN PROGRESS**_

== Project

A Hop Project contains all the files you need to implement a solution.  A Hop Project typically includes the following items:

- Pipelines and Workflows
- Metadata objects
- Reference files
- Data set files
- DDL
- Documentation
- ...
- A file containing project specific settings (TBD: project.json)

We define a project in Hop by giving it a name and by linking that name to a directory. That directory can then contain all the items listed above so that you can check the complete folder into version control (git).

== Project Lifecycle

Sometimes you want to have your Project go through various phases to ensure its quality in what is called a Project Lifecycle.  It defines the sequence of Lifecycle Environments your project goes through to reach a stable production status.

The lifecycle contains the following:
- The names of the project lifecycle environments (see below)
- The filename for a project lifecycle configuration containing the values for lifecycle specific settings (TBD: lifecycle.json).

== Project Lifecycle Environment?

The typical phases in a project lifecycle are: Development, Testing, Acceptance, Production, Continuous Integration and so on.  We call them "Project Lifecycle Environments".
The way this works is that a developer works on a new feature for the project in Development:

- This work is put into version control in a development branch.  At some point the work is ready for testing and a "testing" branch is made in version control. This branch is checked out or copied into another folder or on another server and tested by developers.
- Once a certain level of project maturity has been reached an "acceptance" branch is made and checked out in a different folder or on a different server for testing by end-users.
- When the users are happy with their test results in the "Acceptance" environment the work is branched and tagged as "production".
- When changes are applied to a project in development it's possible to automatically run this revision of the project and see if all is well.  This is called Continuous Integration

Because files in the project need to be moved from one environment to another it's really a bad idea to hard-code any references to host names, folders and so on.  We want to define these with
link:hop-gui/variables/variables.html[Variables]. However, that means that in order to reference a test-server in a "testing" environment or a production-server in a "production" environment you need to be able to set these variables when you're executing a pipeline or workflow. Because of this a Project Lifecycle Environment contains the following items:

- A reference to a Project (the name)
- The filename for a project configuration containing the values for the environment specific settings. (TBD: environment.json)




