////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /metadata-types/
:language: en_US
:page-pagination:

= Neo4j Graph Model

== Description

image:icons/NEO4J.svg[width="24px"]

A graph model describes (part of) a graph by allowing you to define nodes with their properties, and the relationships that connect these nodes.

== Related Plugins

* xref:pipeline/transforms/neo4j-graphoutput.adoc[Neo4j Graph Output]

== Options

[options="header"]
|===
|Option |Description
|Model name|the name to be used for this model
|Description|the description to be used for this model
|Import graph from JSON|import this graph from a JSON file
|Export graph to JSON|export this graph to a JSON file
|Import Cypher Workbench model|Import a model from the Neo4j Cypher Workbench tool (not (yet) publicly available)
|===

== Samples (Integration Tests)

* ./integration-tests/neo4j/tests/neo4j-graph-output/neo4j-cypher-build-graph.hpl